/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnsiLogPanel: typeof import('./components/backtest/AnsiLogPanel.vue')['default']
    BacktestHistoryPanel: typeof import('./components/backtest/BacktestHistoryPanel.vue')['default']
    BacktestResultPanel: typeof import('./components/ultrashort/BacktestResultPanel.vue')['default']
    BacktestSummaryTable: typeof import('./components/backtest/BacktestSummaryTable.vue')['default']
    DataStatusPanel: typeof import('./components/ultrashort/DataStatusPanel.vue')['default']
    LogLevelPanel: typeof import('./components/settings/LogLevelPanel.vue')['default']
    PositionDetailTable: typeof import('./components/position/PositionDetailTable.vue')['default']
    PositionSummaryCards: typeof import('./components/position/PositionSummaryCards.vue')['default']
    PushConfigPanel: typeof import('./components/settings/PushConfigPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/common/SearchBar.vue')['default']
    StockChart: typeof import('./components/charts/StockChart.vue')['default']
    StrategyConfigPanel: typeof import('./components/ultrashort/StrategyConfigPanel.vue')['default']
  }
}
