/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnsiLogPanel: typeof import('./components/backtest/AnsiLogPanel.vue')['default']
    BacktestHistoryPanel: typeof import('./components/backtest/BacktestHistoryPanel.vue')['default']
    BacktestResultPanel: typeof import('./components/ultrashort/BacktestResultPanel.vue')['default']
    BacktestSummaryTable: typeof import('./components/backtest/BacktestSummaryTable.vue')['default']
    DataStatusPanel: typeof import('./components/ultrashort/DataStatusPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FactorReferencePanel: typeof import('./components/ultrashort/FactorReferencePanel.vue')['default']
    LogLevelPanel: typeof import('./components/settings/LogLevelPanel.vue')['default']
    PushConfigPanel: typeof import('./components/settings/PushConfigPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/common/SearchBar.vue')['default']
    StockChart: typeof import('./components/charts/StockChart.vue')['default']
    StrategyConfigPanel: typeof import('./components/ultrashort/StrategyConfigPanel.vue')['default']
    StrategyFactorPanel: typeof import('./components/ultrashort/StrategyFactorPanel.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
